In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy's main datatype is ndarray

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.ndim

1

In [6]:
a1.dtype

dtype('int64')

In [10]:
a1.size

3

In [17]:
a2 = np.array([[1., 2., 3.3],[4., 5., 6.6]])
# a2.ndim
# a2.dtype
# a2.size

## Create a datafram from Numpy Array

In [9]:
import pandas as pd

In [18]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

## 2. Creating Numpy Arrays

In [19]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2, 3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
ones.dtype

dtype('int64')

In [24]:
zeros = np.zeros((2, 3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [37]:
np.random.seed(seed=1)
mat = np.random.randint(0, 10, size=(2, 3, 4, 5))
mat

array([[[[5, 8, 9, 5, 0],
         [0, 1, 7, 6, 9],
         [2, 4, 5, 2, 4],
         [2, 4, 7, 7, 9]],

        [[1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3],
         [9, 8, 7, 3, 6]],

        [[5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9],
         [2, 7, 7, 9, 8]]],


       [[[6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7],
         [9, 7, 3, 0, 8]],

        [[7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8],
         [4, 4, 7, 7, 4]],

        [[9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2],
         [3, 1, 2, 7, 2]]]])

In [27]:
# Pseudo random numbers

 ## Viewing arrays and matrices

In [36]:
# Getting the unique numbers
np.unique(mat)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [45]:
# Matrix Sclicing
mat[-1:,-1:,:1,:4]

array([[[[9, 0, 2, 0]]]])

### Manipulating and comparing arrays

# Arithmatic

In [46]:
a1

array([1, 2, 3])

In [49]:
a1 + ones[0]

array([2, 3, 4])

In [51]:
a1 * ones

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
a1 // ones

array([[1, 2, 3],
       [1, 2, 3]])

In [53]:
a1 ** ones

array([[1, 2, 3],
       [1, 2, 3]])

## Agregation

In [57]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [59]:
# Sum is an aggregation
sum(listy_list)

6

Use python's methods on python datatypes.
Use NumPy's method on Numpy's Arrays


In [60]:
# Create massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [61]:
massive_array[:10]

array([0.44991213, 0.57838961, 0.4081368 , 0.23702698, 0.90337952,
       0.57367949, 0.00287033, 0.61714491, 0.3266449 , 0.5270581 ])

In [63]:
%timeit np.sum(massive_array)
%timeit sum(massive_array)


32.9 µs ± 73.1 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
14.4 ms ± 199 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Reshaping and transposing

In [65]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [67]:
a2.shape

(2, 3)

In [71]:
a2.reshape(2, 3, 1)


array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.6]]])

In [76]:
# Tanspose switches the axis
a2.shape


(2, 3)

In [77]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [73]:
a2.T.shape

(3, 2)

In [74]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.6]])

## Dot product

In [81]:
 mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [82]:
mat1

array([[5, 7, 2],
       [4, 2, 3],
       [4, 5, 9],
       [9, 9, 8],
       [5, 9, 4]])

In [83]:
mat2

array([[7, 7, 9],
       [8, 2, 5],
       [6, 0, 2],
       [6, 1, 9],
       [5, 8, 3]])

In [87]:
mat1.shape, mat2.T.shape, mat2.shape

((5, 3), (3, 5), (5, 3))

In [88]:
mat3 = np.dot(mat1, mat2.T)

In [89]:
mat3

array([[102,  64,  34,  55,  87],
       [ 69,  51,  30,  53,  45],
       [144,  87,  42, 110,  87],
       [198, 130,  70, 135, 141],
       [134,  78,  38,  75, 109]])

In [90]:
mat3.shape

(5, 5)

# Dot product example

In [95]:
np.random.seed(0)
# Numbers of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [97]:
# Weekly sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue", "Wed", "Thu", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [98]:
# Prices
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [100]:
prices_df = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
prices_df

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [103]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [116]:
# weekly_sales.drop(labels="Total", axis=1, inplace=True)
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [117]:
prices_df.shape, weekly_sales.shape

((1, 3), (5, 3))

In [119]:
weekly_df = prices_df.dot(weekly_sales.T)
weekly_df

Mon  Tue  Wed  Thu  Fri
Price  240  138  458  232  142

In [124]:
weekly_sales["Prices ($)"] = weekly_df.T

In [121]:
weekly_df.shape

(1, 5)

In [123]:
weekly_sales.shape

(5, 3)

In [125]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Prices ($)
Mon             12             15              0         240
Tue              3              3              7         138
Wed              9             19             18         458
Thu              4              6             12         232
Fri              1              6              7         142

## Comparison Operators

In [126]:
a1

array([1, 2, 3])

In [127]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [128]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [129]:
a1 < a2

array([[False, False,  True],
       [ True,  True,  True]])

In [130]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting Arrays

In [131]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [132]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

## Practical Example

<img src="panda.png" alt="Panda" />

In [133]:
from matplotlib.image import imread
panda = imread("panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [134]:
panda.size

24465000

In [136]:
panda.shape

(2330, 3500, 3)

<img src="car-photo.png" />

In [137]:
car = imread("car-photo.png")
car[:5]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [138]:
car.ndim, car.size, car.shape

(3, 991300, (431, 575, 4))

<img src="dog-photo.png"/>

In [140]:
dog = imread("dog-photo.png")
dog[:5]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [141]:
dog.ndim, dog.shape, dog.size

(3, (432, 575, 4), 993600)